// Generated by `wit-bindgen` 0.8.0. DO NOT EDIT!
#include "proxy.h"


typedef struct {
  bool is_err;
  union {
    proxy_tuple2_list_u8_bool_t ok;
  } val;
} proxy_result_tuple2_list_u8_bool_stream_error_t;

typedef struct {
  bool is_err;
  union {
    proxy_tuple2_u64_bool_t ok;
  } val;
} proxy_result_tuple2_u64_bool_stream_error_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
  } val;
} proxy_result_u64_stream_error_t;

typedef struct {
  bool is_some;
  wasi_http_types_trailers_t val;
} proxy_option_trailers_t;

typedef struct {
  bool is_some;
  proxy_string_t val;
} proxy_option_string_t;

typedef struct {
  bool is_some;
  wasi_http_types_scheme_t val;
} proxy_option_scheme_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_incoming_stream_t ok;
  } val;
} proxy_result_incoming_stream_void_t;

typedef struct {
  bool is_err;
  union {
    wasi_http_types_outgoing_stream_t ok;
  } val;
} proxy_result_outgoing_stream_void_t;

typedef struct {
  bool is_err;
  union {
  } val;
} proxy_result_void_void_t;

typedef struct {
  bool is_some;
  proxy_result_incoming_response_error_t val;
} proxy_option_result_incoming_response_error_t;

typedef struct {
  bool is_some;
  wasi_http_outgoing_handler_request_options_t val;
} proxy_option_request_options_t;

__attribute__((__import_module__("wasi:clocks/wall-clock"), __import_name__("now")))
void __wasm_import_wasi_clocks_wall_clock_now(int32_t);

__attribute__((__import_module__("wasi:clocks/wall-clock"), __import_name__("resolution")))
void __wasm_import_wasi_clocks_wall_clock_resolution(int32_t);

__attribute__((__import_module__("wasi:poll/poll"), __import_name__("drop-pollable")))
void __wasm_import_wasi_poll_poll_drop_pollable(int32_t);

__attribute__((__import_module__("wasi:poll/poll"), __import_name__("poll-oneoff")))
void __wasm_import_wasi_poll_poll_poll_oneoff(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:clocks/monotonic-clock"), __import_name__("now")))
int64_t __wasm_import_wasi_clocks_monotonic_clock_now(void);

__attribute__((__import_module__("wasi:clocks/monotonic-clock"), __import_name__("resolution")))
int64_t __wasm_import_wasi_clocks_monotonic_clock_resolution(void);

__attribute__((__import_module__("wasi:clocks/monotonic-clock"), __import_name__("subscribe")))
int32_t __wasm_import_wasi_clocks_monotonic_clock_subscribe(int64_t, int32_t);

__attribute__((__import_module__("wasi:clocks/timezone"), __import_name__("display")))
void __wasm_import_wasi_clocks_timezone_display(int32_t, int64_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:clocks/timezone"), __import_name__("utc-offset")))
int32_t __wasm_import_wasi_clocks_timezone_utc_offset(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:clocks/timezone"), __import_name__("drop-timezone")))
void __wasm_import_wasi_clocks_timezone_drop_timezone(int32_t);

__attribute__((__import_module__("wasi:random/random"), __import_name__("get-random-bytes")))
void __wasm_import_wasi_random_random_get_random_bytes(int64_t, int32_t);

__attribute__((__import_module__("wasi:random/random"), __import_name__("get-random-u64")))
int64_t __wasm_import_wasi_random_random_get_random_u64(void);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("read")))
void __wasm_import_wasi_io_streams_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-read")))
void __wasm_import_wasi_io_streams_blocking_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("skip")))
void __wasm_import_wasi_io_streams_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-skip")))
void __wasm_import_wasi_io_streams_blocking_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("subscribe-to-input-stream")))
int32_t __wasm_import_wasi_io_streams_subscribe_to_input_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("drop-input-stream")))
void __wasm_import_wasi_io_streams_drop_input_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("write")))
void __wasm_import_wasi_io_streams_write(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-write")))
void __wasm_import_wasi_io_streams_blocking_write(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("write-zeroes")))
void __wasm_import_wasi_io_streams_write_zeroes(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-write-zeroes")))
void __wasm_import_wasi_io_streams_blocking_write_zeroes(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("splice")))
void __wasm_import_wasi_io_streams_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-splice")))
void __wasm_import_wasi_io_streams_blocking_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("forward")))
void __wasm_import_wasi_io_streams_forward(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("subscribe-to-output-stream")))
int32_t __wasm_import_wasi_io_streams_subscribe_to_output_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("drop-output-stream")))
void __wasm_import_wasi_io_streams_drop_output_stream(int32_t);

__attribute__((__import_module__("wasi:cli/stdout"), __import_name__("get-stdout")))
int32_t __wasm_import_wasi_cli_stdout_get_stdout(void);

__attribute__((__import_module__("wasi:cli/stderr"), __import_name__("get-stderr")))
int32_t __wasm_import_wasi_cli_stderr_get_stderr(void);

__attribute__((__import_module__("wasi:cli/stdin"), __import_name__("get-stdin")))
int32_t __wasm_import_wasi_cli_stdin_get_stdin(void);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-fields")))
void __wasm_import_wasi_http_types_drop_fields(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-fields")))
int32_t __wasm_import_wasi_http_types_new_fields(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-get")))
void __wasm_import_wasi_http_types_fields_get(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-set")))
void __wasm_import_wasi_http_types_fields_set(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-delete")))
void __wasm_import_wasi_http_types_fields_delete(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-append")))
void __wasm_import_wasi_http_types_fields_append(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-entries")))
void __wasm_import_wasi_http_types_fields_entries(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-clone")))
int32_t __wasm_import_wasi_http_types_fields_clone(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("finish-incoming-stream")))
void __wasm_import_wasi_http_types_finish_incoming_stream(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("finish-outgoing-stream")))
void __wasm_import_wasi_http_types_finish_outgoing_stream(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-incoming-request")))
void __wasm_import_wasi_http_types_drop_incoming_request(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-outgoing-request")))
void __wasm_import_wasi_http_types_drop_outgoing_request(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-method")))
void __wasm_import_wasi_http_types_incoming_request_method(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-path-with-query")))
void __wasm_import_wasi_http_types_incoming_request_path_with_query(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-scheme")))
void __wasm_import_wasi_http_types_incoming_request_scheme(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-authority")))
void __wasm_import_wasi_http_types_incoming_request_authority(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-headers")))
int32_t __wasm_import_wasi_http_types_incoming_request_headers(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-consume")))
void __wasm_import_wasi_http_types_incoming_request_consume(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-outgoing-request")))
int32_t __wasm_import_wasi_http_types_new_outgoing_request(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("outgoing-request-write")))
void __wasm_import_wasi_http_types_outgoing_request_write(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-response-outparam")))
void __wasm_import_wasi_http_types_drop_response_outparam(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("set-response-outparam")))
int32_t __wasm_import_wasi_http_types_set_response_outparam(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-incoming-response")))
void __wasm_import_wasi_http_types_drop_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-outgoing-response")))
void __wasm_import_wasi_http_types_drop_outgoing_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-status")))
int32_t __wasm_import_wasi_http_types_incoming_response_status(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-headers")))
int32_t __wasm_import_wasi_http_types_incoming_response_headers(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-consume")))
void __wasm_import_wasi_http_types_incoming_response_consume(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-outgoing-response")))
int32_t __wasm_import_wasi_http_types_new_outgoing_response(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("outgoing-response-write")))
void __wasm_import_wasi_http_types_outgoing_response_write(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-future-incoming-response")))
void __wasm_import_wasi_http_types_drop_future_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("future-incoming-response-get")))
void __wasm_import_wasi_http_types_future_incoming_response_get(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("listen-to-future-incoming-response")))
int32_t __wasm_import_wasi_http_types_listen_to_future_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/outgoing-handler"), __import_name__("handle")))
int32_t __wasm_import_wasi_http_outgoing_handler_handle(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void proxy_list_pollable_free(proxy_list_pollable_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void proxy_list_u8_free(proxy_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wasi_clocks_timezone_timezone_display_free(wasi_clocks_timezone_timezone_display_t *ptr) {
  proxy_string_free(&ptr->name);
}

void proxy_tuple2_list_u8_bool_free(proxy_tuple2_list_u8_bool_t *ptr) {
  proxy_list_u8_free(&ptr->f0);
}

void wasi_http_types_scheme_free(wasi_http_types_scheme_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      proxy_string_free(&ptr->val.other);
      break;
    }
  }
}

void wasi_http_types_method_free(wasi_http_types_method_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 9: {
      proxy_string_free(&ptr->val.other);
      break;
    }
  }
}

void wasi_http_types_error_free(wasi_http_types_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      proxy_string_free(&ptr->val.invalid_url);
      break;
    }
    case 1: {
      proxy_string_free(&ptr->val.timeout_error);
      break;
    }
    case 2: {
      proxy_string_free(&ptr->val.protocol_error);
      break;
    }
    case 3: {
      proxy_string_free(&ptr->val.unexpected_error);
      break;
    }
  }
}

void proxy_tuple2_string_string_free(proxy_tuple2_string_string_t *ptr) {
  proxy_string_free(&ptr->f0);
  proxy_string_free(&ptr->f1);
}

void proxy_list_tuple2_string_string_free(proxy_list_tuple2_string_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    proxy_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void proxy_list_list_u8_free(proxy_list_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    proxy_list_u8_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void proxy_tuple2_string_list_u8_free(proxy_tuple2_string_list_u8_t *ptr) {
  proxy_string_free(&ptr->f0);
  proxy_list_u8_free(&ptr->f1);
}

void proxy_list_tuple2_string_list_u8_free(proxy_list_tuple2_string_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    proxy_tuple2_string_list_u8_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void proxy_result_outgoing_response_error_free(proxy_result_outgoing_response_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_http_types_error_free(&ptr->val.err);
  }
}

void proxy_result_incoming_response_error_free(proxy_result_incoming_response_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_http_types_error_free(&ptr->val.err);
  }
}

void proxy_string_set(proxy_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void proxy_string_dup(proxy_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void proxy_string_free(proxy_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void wasi_clocks_wall_clock_now(wasi_clocks_wall_clock_datetime_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_clocks_wall_clock_now(ptr);
  *ret = (wasi_clocks_wall_clock_datetime_t) {
    (uint64_t) (*((int64_t*) (ptr + 0))),
    (uint32_t) (*((int32_t*) (ptr + 8))),
  };
}

void wasi_clocks_wall_clock_resolution(wasi_clocks_wall_clock_datetime_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_clocks_wall_clock_resolution(ptr);
  *ret = (wasi_clocks_wall_clock_datetime_t) {
    (uint64_t) (*((int64_t*) (ptr + 0))),
    (uint32_t) (*((int32_t*) (ptr + 8))),
  };
}

void wasi_poll_poll_drop_pollable(wasi_poll_poll_pollable_t this) {
  __wasm_import_wasi_poll_poll_drop_pollable((int32_t) (this));
}

void wasi_poll_poll_poll_oneoff(proxy_list_pollable_t *in, proxy_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_poll_poll_poll_oneoff((int32_t) (*in).ptr, (int32_t) (*in).len, ptr);
  *ret = (proxy_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wasi_clocks_monotonic_clock_instant_t wasi_clocks_monotonic_clock_now(void) {
  int64_t ret = __wasm_import_wasi_clocks_monotonic_clock_now();
  return (uint64_t) (ret);
}

wasi_clocks_monotonic_clock_instant_t wasi_clocks_monotonic_clock_resolution(void) {
  int64_t ret = __wasm_import_wasi_clocks_monotonic_clock_resolution();
  return (uint64_t) (ret);
}

wasi_clocks_monotonic_clock_pollable_t wasi_clocks_monotonic_clock_subscribe(wasi_clocks_monotonic_clock_instant_t when, bool absolute) {
  int32_t ret = __wasm_import_wasi_clocks_monotonic_clock_subscribe((int64_t) (when), absolute);
  return (uint32_t) (ret);
}

void wasi_clocks_timezone_display(wasi_clocks_timezone_timezone_t this, wasi_clocks_timezone_datetime_t *when, wasi_clocks_timezone_timezone_display_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_clocks_timezone_display((int32_t) (this), (int64_t) ((*when).seconds), (int32_t) ((*when).nanoseconds), ptr);
  *ret = (wasi_clocks_timezone_timezone_display_t) {
    *((int32_t*) (ptr + 0)),
    (proxy_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
    (int32_t) (*((uint8_t*) (ptr + 12))),
  };
}

int32_t wasi_clocks_timezone_utc_offset(wasi_clocks_timezone_timezone_t this, wasi_clocks_timezone_datetime_t *when) {
  int32_t ret = __wasm_import_wasi_clocks_timezone_utc_offset((int32_t) (this), (int64_t) ((*when).seconds), (int32_t) ((*when).nanoseconds));
  return ret;
}

void wasi_clocks_timezone_drop_timezone(wasi_clocks_timezone_timezone_t this) {
  __wasm_import_wasi_clocks_timezone_drop_timezone((int32_t) (this));
}

void wasi_random_random_get_random_bytes(uint64_t len, proxy_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_random_random_get_random_bytes((int64_t) (len), ptr);
  *ret = (proxy_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wasi_random_random_get_random_u64(void) {
  int64_t ret = __wasm_import_wasi_random_random_get_random_u64();
  return (uint64_t) (ret);
}

bool wasi_io_streams_read(wasi_io_streams_input_stream_t this, uint64_t len, proxy_tuple2_list_u8_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_read((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_tuple2_list_u8_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_list_u8_bool_t) {
        (proxy_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (int32_t) (*((uint8_t*) (ptr + 12))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_blocking_read(wasi_io_streams_input_stream_t this, uint64_t len, proxy_tuple2_list_u8_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_read((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_tuple2_list_u8_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_list_u8_bool_t) {
        (proxy_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (int32_t) (*((uint8_t*) (ptr + 12))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_skip(wasi_io_streams_input_stream_t this, uint64_t len, proxy_tuple2_u64_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_skip((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_tuple2_u64_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_u64_bool_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_blocking_skip(wasi_io_streams_input_stream_t this, uint64_t len, proxy_tuple2_u64_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_skip((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_tuple2_u64_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_u64_bool_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_io_streams_pollable_t wasi_io_streams_subscribe_to_input_stream(wasi_io_streams_input_stream_t this) {
  int32_t ret = __wasm_import_wasi_io_streams_subscribe_to_input_stream((int32_t) (this));
  return (uint32_t) (ret);
}

void wasi_io_streams_drop_input_stream(wasi_io_streams_input_stream_t this) {
  __wasm_import_wasi_io_streams_drop_input_stream((int32_t) (this));
}

bool wasi_io_streams_write(wasi_io_streams_output_stream_t this, proxy_list_u8_t *buf, uint64_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_write((int32_t) (this), (int32_t) (*buf).ptr, (int32_t) (*buf).len, ptr);
  proxy_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_blocking_write(wasi_io_streams_output_stream_t this, proxy_list_u8_t *buf, uint64_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_write((int32_t) (this), (int32_t) (*buf).ptr, (int32_t) (*buf).len, ptr);
  proxy_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_write_zeroes(wasi_io_streams_output_stream_t this, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_write_zeroes((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_blocking_write_zeroes(wasi_io_streams_output_stream_t this, uint64_t len, uint64_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_write_zeroes((int32_t) (this), (int64_t) (len), ptr);
  proxy_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_splice(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, uint64_t len, proxy_tuple2_u64_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_splice((int32_t) (this), (int32_t) (src), (int64_t) (len), ptr);
  proxy_result_tuple2_u64_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_u64_bool_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_blocking_splice(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, uint64_t len, proxy_tuple2_u64_bool_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_splice((int32_t) (this), (int32_t) (src), (int64_t) (len), ptr);
  proxy_result_tuple2_u64_bool_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (proxy_tuple2_u64_bool_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

bool wasi_io_streams_forward(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, uint64_t *ret, wasi_io_streams_stream_error_t *err) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_forward((int32_t) (this), (int32_t) (src), ptr);
  proxy_result_u64_stream_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint64_t) (*((int64_t*) (ptr + 8)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_io_streams_pollable_t wasi_io_streams_subscribe_to_output_stream(wasi_io_streams_output_stream_t this) {
  int32_t ret = __wasm_import_wasi_io_streams_subscribe_to_output_stream((int32_t) (this));
  return (uint32_t) (ret);
}

void wasi_io_streams_drop_output_stream(wasi_io_streams_output_stream_t this) {
  __wasm_import_wasi_io_streams_drop_output_stream((int32_t) (this));
}

wasi_cli_stdout_output_stream_t wasi_cli_stdout_get_stdout(void) {
  int32_t ret = __wasm_import_wasi_cli_stdout_get_stdout();
  return (uint32_t) (ret);
}

wasi_cli_stderr_output_stream_t wasi_cli_stderr_get_stderr(void) {
  int32_t ret = __wasm_import_wasi_cli_stderr_get_stderr();
  return (uint32_t) (ret);
}

wasi_cli_stdin_input_stream_t wasi_cli_stdin_get_stdin(void) {
  int32_t ret = __wasm_import_wasi_cli_stdin_get_stdin();
  return (uint32_t) (ret);
}

void wasi_http_types_drop_fields(wasi_http_types_fields_t fields) {
  __wasm_import_wasi_http_types_drop_fields((int32_t) (fields));
}

wasi_http_types_fields_t wasi_http_types_new_fields(proxy_list_tuple2_string_string_t *entries) {
  int32_t ret = __wasm_import_wasi_http_types_new_fields((int32_t) (*entries).ptr, (int32_t) (*entries).len);
  return (uint32_t) (ret);
}

void wasi_http_types_fields_get(wasi_http_types_fields_t fields, proxy_string_t *name, proxy_list_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_fields_get((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, ptr);
  *ret = (proxy_list_list_u8_t) { (proxy_list_u8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_http_types_fields_set(wasi_http_types_fields_t fields, proxy_string_t *name, proxy_list_list_u8_t *value) {
  __wasm_import_wasi_http_types_fields_set((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) (*value).ptr, (int32_t) (*value).len);
}

void wasi_http_types_fields_delete(wasi_http_types_fields_t fields, proxy_string_t *name) {
  __wasm_import_wasi_http_types_fields_delete((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len);
}

void wasi_http_types_fields_append(wasi_http_types_fields_t fields, proxy_string_t *name, proxy_list_u8_t *value) {
  __wasm_import_wasi_http_types_fields_append((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) (*value).ptr, (int32_t) (*value).len);
}

void wasi_http_types_fields_entries(wasi_http_types_fields_t fields, proxy_list_tuple2_string_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_fields_entries((int32_t) (fields), ptr);
  *ret = (proxy_list_tuple2_string_list_u8_t) { (proxy_tuple2_string_list_u8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wasi_http_types_fields_t wasi_http_types_fields_clone(wasi_http_types_fields_t fields) {
  int32_t ret = __wasm_import_wasi_http_types_fields_clone((int32_t) (fields));
  return (uint32_t) (ret);
}

bool wasi_http_types_finish_incoming_stream(wasi_http_types_incoming_stream_t s, wasi_http_types_trailers_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_finish_incoming_stream((int32_t) (s), ptr);
  proxy_option_trailers_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

void wasi_http_types_finish_outgoing_stream(wasi_http_types_outgoing_stream_t s, wasi_http_types_trailers_t *maybe_trailers) {
  proxy_option_trailers_t trailers;
  trailers.is_some = maybe_trailers != NULL;if (maybe_trailers) {
    trailers.val = *maybe_trailers;
  }
  int32_t option;
  int32_t option1;
  if ((trailers).is_some) {
    const wasi_http_types_trailers_t *payload0 = &(trailers).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  __wasm_import_wasi_http_types_finish_outgoing_stream((int32_t) (s), option, option1);
}

void wasi_http_types_drop_incoming_request(wasi_http_types_incoming_request_t request) {
  __wasm_import_wasi_http_types_drop_incoming_request((int32_t) (request));
}

void wasi_http_types_drop_outgoing_request(wasi_http_types_outgoing_request_t request) {
  __wasm_import_wasi_http_types_drop_outgoing_request((int32_t) (request));
}

void wasi_http_types_incoming_request_method(wasi_http_types_incoming_request_t request, wasi_http_types_method_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_method((int32_t) (request), ptr);
  wasi_http_types_method_t variant;
  variant.tag = (int32_t) (*((uint8_t*) (ptr + 0)));
  switch ((int32_t) variant.tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    case 2: {
      break;
    }
    case 3: {
      break;
    }
    case 4: {
      break;
    }
    case 5: {
      break;
    }
    case 6: {
      break;
    }
    case 7: {
      break;
    }
    case 8: {
      break;
    }
    case 9: {
      variant.val.other = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = variant;
}

bool wasi_http_types_incoming_request_path_with_query(wasi_http_types_incoming_request_t request, proxy_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_path_with_query((int32_t) (request), ptr);
  proxy_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool wasi_http_types_incoming_request_scheme(wasi_http_types_incoming_request_t request, wasi_http_types_scheme_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_scheme((int32_t) (request), ptr);
  proxy_option_scheme_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      wasi_http_types_scheme_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          variant.val.other = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 8))), (size_t)(*((int32_t*) (ptr + 12))) };
          break;
        }
      }
      
      option.val = variant;
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool wasi_http_types_incoming_request_authority(wasi_http_types_incoming_request_t request, proxy_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_authority((int32_t) (request), ptr);
  proxy_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

wasi_http_types_headers_t wasi_http_types_incoming_request_headers(wasi_http_types_incoming_request_t request) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_request_headers((int32_t) (request));
  return (uint32_t) (ret);
}

bool wasi_http_types_incoming_request_consume(wasi_http_types_incoming_request_t request, wasi_http_types_incoming_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_consume((int32_t) (request), ptr);
  proxy_result_incoming_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_http_types_outgoing_request_t wasi_http_types_new_outgoing_request(wasi_http_types_method_t *method, proxy_string_t *maybe_path_with_query, wasi_http_types_scheme_t *maybe_scheme, proxy_string_t *maybe_authority, wasi_http_types_headers_t headers) {
  proxy_option_string_t path_with_query;
  path_with_query.is_some = maybe_path_with_query != NULL;if (maybe_path_with_query) {
    path_with_query.val = *maybe_path_with_query;
  }
  proxy_option_scheme_t scheme;
  scheme.is_some = maybe_scheme != NULL;if (maybe_scheme) {
    scheme.val = *maybe_scheme;
  }
  proxy_option_string_t authority;
  authority.is_some = maybe_authority != NULL;if (maybe_authority) {
    authority.val = *maybe_authority;
  }
  int32_t variant;
  int32_t variant9;
  int32_t variant10;
  switch ((int32_t) (*method).tag) {
    case 0: {
      variant = 0;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 3: {
      variant = 3;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 4: {
      variant = 4;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 5: {
      variant = 5;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 6: {
      variant = 6;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 7: {
      variant = 7;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 8: {
      variant = 8;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 9: {
      const proxy_string_t *payload8 = &(*method).val.other;
      variant = 9;
      variant9 = (int32_t) (*payload8).ptr;
      variant10 = (int32_t) (*payload8).len;
      break;
    }
  }
  int32_t option;
  int32_t option13;
  int32_t option14;
  if ((path_with_query).is_some) {
    const proxy_string_t *payload12 = &(path_with_query).val;
    option = 1;
    option13 = (int32_t) (*payload12).ptr;
    option14 = (int32_t) (*payload12).len;
  } else {
    option = 0;
    option13 = 0;
    option14 = 0;
  }
  int32_t option23;
  int32_t option24;
  int32_t option25;
  int32_t option26;
  if ((scheme).is_some) {
    const wasi_http_types_scheme_t *payload16 = &(scheme).val;
    int32_t variant20;
    int32_t variant21;
    int32_t variant22;
    switch ((int32_t) (*payload16).tag) {
      case 0: {
        variant20 = 0;
        variant21 = 0;
        variant22 = 0;
        break;
      }
      case 1: {
        variant20 = 1;
        variant21 = 0;
        variant22 = 0;
        break;
      }
      case 2: {
        const proxy_string_t *payload19 = &(*payload16).val.other;
        variant20 = 2;
        variant21 = (int32_t) (*payload19).ptr;
        variant22 = (int32_t) (*payload19).len;
        break;
      }
    }
    option23 = 1;
    option24 = variant20;
    option25 = variant21;
    option26 = variant22;
  } else {
    option23 = 0;
    option24 = 0;
    option25 = 0;
    option26 = 0;
  }
  int32_t option29;
  int32_t option30;
  int32_t option31;
  if ((authority).is_some) {
    const proxy_string_t *payload28 = &(authority).val;
    option29 = 1;
    option30 = (int32_t) (*payload28).ptr;
    option31 = (int32_t) (*payload28).len;
  } else {
    option29 = 0;
    option30 = 0;
    option31 = 0;
  }
  int32_t ret = __wasm_import_wasi_http_types_new_outgoing_request(variant, variant9, variant10, option, option13, option14, option23, option24, option25, option26, option29, option30, option31, (int32_t) (headers));
  return (uint32_t) (ret);
}

bool wasi_http_types_outgoing_request_write(wasi_http_types_outgoing_request_t request, wasi_http_types_outgoing_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_outgoing_request_write((int32_t) (request), ptr);
  proxy_result_outgoing_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

void wasi_http_types_drop_response_outparam(wasi_http_types_response_outparam_t response) {
  __wasm_import_wasi_http_types_drop_response_outparam((int32_t) (response));
}

bool wasi_http_types_set_response_outparam(wasi_http_types_response_outparam_t param, proxy_result_outgoing_response_error_t *response) {
  int32_t result;
  int32_t result7;
  int32_t result8;
  int32_t result9;
  if ((*response).is_err) {
    const wasi_http_types_error_t *payload0 = &(*response).val.err;int32_t variant;
    int32_t variant5;
    int32_t variant6;
    switch ((int32_t) (*payload0).tag) {
      case 0: {
        const proxy_string_t *payload1 = &(*payload0).val.invalid_url;
        variant = 0;
        variant5 = (int32_t) (*payload1).ptr;
        variant6 = (int32_t) (*payload1).len;
        break;
      }
      case 1: {
        const proxy_string_t *payload2 = &(*payload0).val.timeout_error;
        variant = 1;
        variant5 = (int32_t) (*payload2).ptr;
        variant6 = (int32_t) (*payload2).len;
        break;
      }
      case 2: {
        const proxy_string_t *payload3 = &(*payload0).val.protocol_error;
        variant = 2;
        variant5 = (int32_t) (*payload3).ptr;
        variant6 = (int32_t) (*payload3).len;
        break;
      }
      case 3: {
        const proxy_string_t *payload4 = &(*payload0).val.unexpected_error;
        variant = 3;
        variant5 = (int32_t) (*payload4).ptr;
        variant6 = (int32_t) (*payload4).len;
        break;
      }
    }
    result = 1;
    result7 = variant;
    result8 = variant5;
    result9 = variant6;
  } else {
    const wasi_http_types_outgoing_response_t *payload = &(*response).val.ok;result = 0;
    result7 = (int32_t) (*payload);
    result8 = 0;
    result9 = 0;
  }
  int32_t ret = __wasm_import_wasi_http_types_set_response_outparam((int32_t) (param), result, result7, result8, result9);
  proxy_result_void_void_t result10;
  switch (ret) {
    case 0: {
      result10.is_err = false;
      break;
    }
    case 1: {
      result10.is_err = true;
      break;
    }
  }
  if (!result10.is_err) {
    return 1;
  } else {
    return 0;
  }
}

void wasi_http_types_drop_incoming_response(wasi_http_types_incoming_response_t response) {
  __wasm_import_wasi_http_types_drop_incoming_response((int32_t) (response));
}

void wasi_http_types_drop_outgoing_response(wasi_http_types_outgoing_response_t response) {
  __wasm_import_wasi_http_types_drop_outgoing_response((int32_t) (response));
}

wasi_http_types_status_code_t wasi_http_types_incoming_response_status(wasi_http_types_incoming_response_t response) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_response_status((int32_t) (response));
  return (uint16_t) (ret);
}

wasi_http_types_headers_t wasi_http_types_incoming_response_headers(wasi_http_types_incoming_response_t response) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_response_headers((int32_t) (response));
  return (uint32_t) (ret);
}

bool wasi_http_types_incoming_response_consume(wasi_http_types_incoming_response_t response, wasi_http_types_incoming_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_response_consume((int32_t) (response), ptr);
  proxy_result_incoming_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

wasi_http_types_outgoing_response_t wasi_http_types_new_outgoing_response(wasi_http_types_status_code_t status_code, wasi_http_types_headers_t headers) {
  int32_t ret = __wasm_import_wasi_http_types_new_outgoing_response((int32_t) (status_code), (int32_t) (headers));
  return (uint32_t) (ret);
}

bool wasi_http_types_outgoing_response_write(wasi_http_types_outgoing_response_t response, wasi_http_types_outgoing_stream_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_outgoing_response_write((int32_t) (response), ptr);
  proxy_result_outgoing_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    return 0;
  }
}

void wasi_http_types_drop_future_incoming_response(wasi_http_types_future_incoming_response_t f) {
  __wasm_import_wasi_http_types_drop_future_incoming_response((int32_t) (f));
}

bool wasi_http_types_future_incoming_response_get(wasi_http_types_future_incoming_response_t f, proxy_result_incoming_response_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_future_incoming_response_get((int32_t) (f), ptr);
  proxy_option_result_incoming_response_error_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      proxy_result_incoming_response_error_t result;
      switch ((int32_t) (*((uint8_t*) (ptr + 4)))) {
        case 0: {
          result.is_err = false;
          result.val.ok = (uint32_t) (*((int32_t*) (ptr + 8)));
          break;
        }
        case 1: {
          result.is_err = true;
          wasi_http_types_error_t variant;
          variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
          switch ((int32_t) variant.tag) {
            case 0: {
              variant.val.invalid_url = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 1: {
              variant.val.timeout_error = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 2: {
              variant.val.protocol_error = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 3: {
              variant.val.unexpected_error = (proxy_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
          }
          
          result.val.err = variant;
          break;
        }
      }
      
      option.val = result;
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

wasi_http_types_pollable_t wasi_http_types_listen_to_future_incoming_response(wasi_http_types_future_incoming_response_t f) {
  int32_t ret = __wasm_import_wasi_http_types_listen_to_future_incoming_response((int32_t) (f));
  return (uint32_t) (ret);
}

wasi_http_outgoing_handler_future_incoming_response_t wasi_http_outgoing_handler_handle(wasi_http_outgoing_handler_outgoing_request_t request, wasi_http_outgoing_handler_request_options_t *maybe_options) {
  proxy_option_request_options_t options;
  options.is_some = maybe_options != NULL;if (maybe_options) {
    options.val = *maybe_options;
  }
  int32_t option12;
  int32_t option13;
  int32_t option14;
  int32_t option15;
  int32_t option16;
  int32_t option17;
  int32_t option18;
  if ((options).is_some) {
    const wasi_http_outgoing_handler_request_options_t *payload0 = &(options).val;
    int32_t option;
    int32_t option3;
    if (((*payload0).connect_timeout_ms).is_some) {
      const uint32_t *payload2 = &((*payload0).connect_timeout_ms).val;
      option = 1;
      option3 = (int32_t) (*payload2);
    } else {
      option = 0;
      option3 = 0;
    }
    int32_t option6;
    int32_t option7;
    if (((*payload0).first_byte_timeout_ms).is_some) {
      const uint32_t *payload5 = &((*payload0).first_byte_timeout_ms).val;
      option6 = 1;
      option7 = (int32_t) (*payload5);
    } else {
      option6 = 0;
      option7 = 0;
    }
    int32_t option10;
    int32_t option11;
    if (((*payload0).between_bytes_timeout_ms).is_some) {
      const uint32_t *payload9 = &((*payload0).between_bytes_timeout_ms).val;
      option10 = 1;
      option11 = (int32_t) (*payload9);
    } else {
      option10 = 0;
      option11 = 0;
    }
    option12 = 1;
    option13 = option;
    option14 = option3;
    option15 = option6;
    option16 = option7;
    option17 = option10;
    option18 = option11;
  } else {
    option12 = 0;
    option13 = 0;
    option14 = 0;
    option15 = 0;
    option16 = 0;
    option17 = 0;
    option18 = 0;
  }
  int32_t ret = __wasm_import_wasi_http_outgoing_handler_handle((int32_t) (request), option12, option13, option14, option15, option16, option17, option18);
  return (uint32_t) (ret);
}

__attribute__((__export_name__("wasi:http/incoming-handler#handle")))
void __wasm_export_exports_wasi_http_incoming_handler_handle(int32_t arg, int32_t arg0) {
  exports_wasi_http_incoming_handler_handle((uint32_t) (arg), (uint32_t) (arg0));
}

extern void __component_type_object_force_link_proxy(void);
void __component_type_object_force_link_proxy_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_proxy();
}
